name: shopify_app
description: A mini e-commerce Flutter app for CyphLab internship task.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
